### ISSUE TITLE
Unable to compile -Arch Linux

### ISSUE THREAD

**Issue by trogers121** [juliagoda/CH341SER#19]
I ran into an issue where I was unable to compile the driver following the instructions presented here.

Navigating into the repo directory and running make:

`make`
`make -C /lib/modules/5.15.6-arch2-1/build  M=/home/user/CH341SER `
`make[1]: *** /lib/modules/5.15.6-arch2-1/build: No such file or directory.  Stop.`
`make: *** [Makefile:7: default] Error 2`

I then created the directory with:
`sudo mkdir /lib/modules/5.15.6-arch2-1/build`

Re-running make generates:
`make`
`make -C /lib/modules/5.15.6-arch2-1/build  M=/home/user/CH341SER `
`make[1]: Entering directory '/usr/lib/modules/5.15.6-arch2-1/build'`
`make[1]: *** No targets specified and no makefile found.  Stop.`
`make[1]: Leaving directory '/usr/lib/modules/5.15.6-arch2-1/build'`
`make: *** [Makefile:7: default] Error 2`

I then found that a reddit post that indicated that the linux-headers package needs to be installed: [https://www.reddit.com/r/archlinux/comments/8j53dq/comment/dyx43om/?utm_source=share&utm_medium=web2x&context=3](url)

`sudo pacman -S linux-headers`

I was then finally able to compile the driver.

It may make the installation easier to provide a list of dependencies for building the driver.

**Comment by juliagoda** [comment]
ac24bab084f243ac7954754a7f1ac5d753abc6c2
