### ISSUE TITLE
Showing that make[1]: *** No targets specified and no makefile found. 

### ISSUE THREAD

**Issue by amitkray31** [juliagoda/CH341SER#2]
make -C /lib/modules/4.19.6-1-MANJARO/build  M=/home/akr/Downloads/CH341SER-master 
make[1]: Entering directory '/usr/lib/modules/4.19.6-1-MANJARO/build'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/usr/lib/modules/4.19.6-1-MANJARO/build'
make: *** [Makefile:7: default] Error 2

OS:- Manjaor linux
Linux Kernel 4.19.6-1 LTS

**Comment by juliagoda** [comment]
make -C some_directory should contain Makefile from project. Below is a result of building on my computer:

```
[juliagoda@juliagoda]: ~/Github/CH341SER/build>$ make -C ..
make: Wejście do katalogu '/home/juliagoda/Github/CH341SER'
make -C /lib/modules/4.19.2.ll5-2-juliagoda-git/build  M=/home/juliagoda/Github/CH341SER 
make[1]: Wejście do katalogu '/usr/lib/modules/4.19.2.ll5-2-juliagoda-git/build'
  Building modules, stage 2.
  MODPOST 1 modules
make[1]: Opuszczenie katalogu '/usr/lib/modules/4.19.2.ll5-2-juliagoda-git/build'
make: Opuszczenie katalogu '/home/juliagoda/Github/CH341SER'
```
in your case it would be:
`make -C /home/akr/Downloads/CH341SER-master`


Source:
[Make options](https://www.computerhope.com/unix/umake.htm)

**Comment by amitkray31** [comment]
I used this command `git clone https://github.com/juliagoda/CH341SER.git` and cloned it on **/home/akr**
directory. What to do next if you please tell me step wise.

```
ifeq ($(KERNELRELEASE), )

KERNELDIR := /lib/modules/$(shell uname -r)/build

PWD :=$(shell pwd)
default:
	$(MAKE) -C $(KERNELDIR)  M=$(PWD) 
clean:
	rm -rf .tmp_versions Module.symvers *.mod.c *.o *.ko .*.cmd Module.markers modules.order
load:
	modprobe usbserial
	insmod ch34x.ko
unload:
	rmmod ch34x
else
	obj-m := ch34x.o
endif
```

**Comment by juliagoda** [comment]
```
cd /home/akr
make
make load
```
Everything is written in readme.txt. Please next time send me email or read more about commands, because it's not even an issue. I am closing it
