### ISSUE TITLE
module verification failed: signature and/or required key missing - tainting kernel

### ISSUE THREAD

**Issue by Krbija** [juliagoda/CH341SER#7]
hello

i'm follow the readme.txt install this driver on Ubuntu 18.04, but it's not work.

```sh
uname -a

Linux lxeo 5.4.0-45-generic #49~18.04.2-Ubuntu SMP Wed Aug 26 16:29:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
``` 

```sh
lsmod | grep ch34

ch34x                  24576  0
usbserial              49152  1 ch34x
```

```sh
dmesg | grep ch34

[   57.989423] ch34x: loading out-of-tree module taints kernel.
[   57.989477] ch34x: module verification failed: signature and/or required key missing - tainting kernel
[   57.989761] usbcore: registered new interface driver ch34x
[   57.989789] usbserial: USB Serial support registered for ch34x
[  269.528281] usbserial: USB Serial deregistering driver ch34x
[  269.528331] usbcore: deregistering interface driver ch34x
[  272.788150] usbcore: registered new interface driver ch34x
[  272.788168] usbserial: USB Serial support registered for ch34x
```

```sh
ls /dev/ttyUSB*

zsh: no matches found: /dev/ttyUSB*
```

**Comment by juliagoda** [comment]
Even if you have the same warnings, check the work of module and tell me about results

**Comment by Esther-99** [comment]
Hello, I have the same problem here on Ubuntu 18.04. Is there any solutions?

**Comment by hesaputra** [comment]
Did you sign the compiled ch34x.ko? 

`
openssl req -new -x509 -newkey rsa:2048 -keyout MOK.priv -outform DER -out MOK.der -nodes -days 36500 -subj "/CN=Descriptive name/"
`

`
sudo /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ./MOK.priv ./MOK.der ch34x.ko
`

`
sudo mokutil --import MOK.der
`

`
Enter your password, reboot, then load the key
`

**Comment by Esther-99** [comment]
> Did you sign the compiled ch34x.ko?
> 
> `openssl req -new -x509 -newkey rsa:2048 -keyout MOK.priv -outform DER -out MOK.der -nodes -days 36500 -subj "/CN=Descriptive name/"`
> 
> `sudo /usr/src/linux-headers-$(uname -r)/scripts/sign-file sha256 ./MOK.priv ./MOK.der ch34x.ko`
> 
> `sudo mokutil --import MOK.der`
> 
> `Enter your password, reboot, then load the key`

Thanks for your suggestion! Now the warning disappears but still no conversion is made:
![image](https://user-images.githubusercontent.com/56192986/104345719-a08ca200-5539-11eb-8c87-dac2c34a633b.png)
Looks like the conversion problem is not related with the verification. Are there any other causes for the problem?

**Comment by hesaputra** [comment]
What device are you trying to connect to? the idVendor and idProduct from your screenshot don't seems to match with ch341x signature.  Perhaps your device need another driver, not this one. 
From the source code:
`
#define CH34x_VENDOR_ID 0x1A86
`

`
#define CH340_PRODUCT_ID	0x7523
`

`
#define CH341_PRODUCT_ID	0x5523
`

**Comment by Esther-99** [comment]
Thanks for your suggestion. Seems that I should look for other drivers.

**Comment by juliagoda** [comment]
Thank you @hesaputra  for help and sorry for being late. Closed.

**Comment by humblepenguinn** [comment]
How can I fix this on a Arch based system? The sign-file script is not available
