### ISSUE TITLE
Make detects "no control file" & Make load displays "Invalid module format"

### ISSUE THREAD

**Issue by 18iteration** [juliagoda/CH341SER#9]
_I am so done with this. This is without a doubt the worst error ever, I hate make._

When I try to execute `sudo make` in the CH341SER folder, it simply enters the modules/....../amd64/build foldder and leaves because no destination or `make` control file was named.

When using the InstallACModule's "InstallCH340.sh" file, I finally have a ch34x.ko. So I tried to copy the file to the CH341SER folder and then wrote `sudo make load. 
Except now I get the error 

_modprobe usbserial
insmod ch34x.ko
insmod: ERROR: could not insert module ch34x.ko: Invalid module format
make: *** [Makefile:12: load] Error 1_

EDIT: Please help, put an end to this extrodinary suffering

**Comment by nsk** [comment]
known bug you must connect the sensor directly to the GPIOs and to the sensor

**Comment by 18iteration** [comment]
No no you misunderstood something or I didnt clarify my case well enough.
I haven't even written a sketch, I can't see my nano in arduino IDE because the drivers are not installed
